// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKnqnu4ESl2Iw_d_HctvULmKt-_vBDla0',
    appId: '1:628841847510:web:e52d03de22a46293b6c777',
    messagingSenderId: '628841847510',
    projectId: 'hasnetix-prod',
    authDomain: 'hasnetix-prod.firebaseapp.com',
    storageBucket: 'hasnetix-prod.firebasestorage.app',
    measurementId: 'G-1Z0JD4PCXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzEtlDr10V0uvXO0ifOPLq4ByDpPf5E18',
    appId: '1:628841847510:android:3789024ab47fc812b6c777',
    messagingSenderId: '628841847510',
    projectId: 'hasnetix-prod',
    storageBucket: 'hasnetix-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDPFRc112PDo69Ep9MHPey68IxlT18GTc',
    appId: '1:628841847510:ios:c5b723974ed5c314b6c777',
    messagingSenderId: '628841847510',
    projectId: 'hasnetix-prod',
    storageBucket: 'hasnetix-prod.firebasestorage.app',
    iosBundleId: 'com.hasneticlabs.hasnetix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDPFRc112PDo69Ep9MHPey68IxlT18GTc',
    appId: '1:628841847510:ios:c5b723974ed5c314b6c777',
    messagingSenderId: '628841847510',
    projectId: 'hasnetix-prod',
    storageBucket: 'hasnetix-prod.firebasestorage.app',
    iosBundleId: 'com.hasneticlabs.hasnetix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKnqnu4ESl2Iw_d_HctvULmKt-_vBDla0',
    appId: '1:628841847510:web:9f51f3e991e754d0b6c777',
    messagingSenderId: '628841847510',
    projectId: 'hasnetix-prod',
    authDomain: 'hasnetix-prod.firebaseapp.com',
    storageBucket: 'hasnetix-prod.firebasestorage.app',
    measurementId: 'G-9SFRSWGT8C',
  );
}
