// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_XCHVC5zn2fsLFkd4qe5JbsgyNUzx1b8',
    appId: '1:403975644133:web:60586a3b6e1fe1a41e850c',
    messagingSenderId: '403975644133',
    projectId: 'hasnetix-stage',
    authDomain: 'hasnetix-stage.firebaseapp.com',
    storageBucket: 'hasnetix-stage.firebasestorage.app',
    measurementId: 'G-C48F944WQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRI8dUskbxkgLYMvVItmlGqhMB3NvGL4c',
    appId: '1:403975644133:android:7f8e2098359489861e850c',
    messagingSenderId: '403975644133',
    projectId: 'hasnetix-stage',
    storageBucket: 'hasnetix-stage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4tVDMnYMMeMTyDIhSAFIt18FEvaHftkE',
    appId: '1:403975644133:ios:39fc76999287cd2b1e850c',
    messagingSenderId: '403975644133',
    projectId: 'hasnetix-stage',
    storageBucket: 'hasnetix-stage.firebasestorage.app',
    iosBundleId: 'com.hasneticlabs.hasnetix.stage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4tVDMnYMMeMTyDIhSAFIt18FEvaHftkE',
    appId: '1:403975644133:ios:39fc76999287cd2b1e850c',
    messagingSenderId: '403975644133',
    projectId: 'hasnetix-stage',
    storageBucket: 'hasnetix-stage.firebasestorage.app',
    iosBundleId: 'com.hasneticlabs.hasnetix.stage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_XCHVC5zn2fsLFkd4qe5JbsgyNUzx1b8',
    appId: '1:403975644133:web:fffa0b55337901881e850c',
    messagingSenderId: '403975644133',
    projectId: 'hasnetix-stage',
    authDomain: 'hasnetix-stage.firebaseapp.com',
    storageBucket: 'hasnetix-stage.firebasestorage.app',
    measurementId: 'G-LYNFP5Q5DG',
  );
}